version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./webapp/static/images:/app/webapp/static/images
      - /home/jan/Desktop/test:/data
    environment:
      - FLASK_ENV=development
